### ISSUE TITLE
Update .website to reference the 1.6 web application

### ISSUE THREAD

**Issue by boisei0** [ApparyllisOrg/Spot#1]
The .website command of Spot still tells users that a web portal isn't likely to be added. With 1.6, a portal has been added. 
Current text shows as below:

https://github.com/ApparyllisOrg/Spot/blob/dffb46f6235c7083bbbc5593accfe1689eaf05bf/messages.js#L225-L232

Updated text could be something like:

> "Version 1.6 of Simply Plural introduced a web portal. It is available at [link]."

**Comment by Cellaryllis** [comment]
@boisei0 oh sorry I never got notified for this and I didn't really pay attention to this repo. We're switching over to messages.json in the near future but it seems like it's also been taken care of already outside of this PR. Thanks for the PR tho!
